//I'm Alice

export const messages1: Message[] = [
  {
    id: 1,
    content: "Salut, comment ça va ...",
    createdAt: "2021-12-16T09:00:00Z",
    updatedAt: "2021-12-16T09:00:00Z",
    isRead: true,
    sender: { username: "Alice", email: "carelli@gmail.com" },
    receiver: { username: "Bob", email: "BOB@gmail.com" },
  },
  {
    id: 2,
    content: "Ça va bien, merci!",
    createdAt: "2021-12-16T09:05:00Z",
    updatedAt: "2021-12-16T09:05:00Z",
    isRead: true,
    sender: { username: "Bob", email: "BOB@gmail.com" },
    receiver: { username: "Alice", email: "carelli@gmail.com" },
  },
  {
    id: 3,
    content: "Qu'as-tu prévu pour aujourd'hui?",
    createdAt: "2021-12-16T09:10:00Z",
    updatedAt: "2021-12-16T09:10:00Z",
    isRead: false,
    sender: { username: "Alice", email: "carelli@gmail.com" },
    receiver: { username: "Bob", email: "BOB@gmail.com" },
  },
  {
    id: 4,
    content: "Rien de spécial, juste du travail.",
    createdAt: "2021-12-16T09:15:00Z",
    updatedAt: "2021-12-16T09:15:00Z",
    isRead: false,
    sender: { username: "Bob", email: "BOB@gmail.com" },
    receiver: { username: "Alice", email: "carelli@gmail.com" },
  },
];

export const messages2: Message[] = [
  {
    id: 1,
    content: "Salut Kevin, comment ça va?",
    createdAt: "2022-01-10T09:00:00Z",
    updatedAt: "2022-01-10T09:00:00Z",
    isRead: true,
    sender: { username: "Alice", email: "carelli@gmail.com" },
    receiver: { username: "Kevin", email: "kevin@gmail.com" },
  },
  {
    id: 2,
    content: "Salut Alice, je vais bien, merci! Et toi?",
    createdAt: "2022-01-10T09:05:00Z",
    updatedAt: "2022-01-10T09:05:00Z",
    isRead: true,
    sender: { username: "Kevin", email: "kevin@gmail.com" },
    receiver: { username: "Alice", email: "carelli@gmail.com" },
  },
  {
    id: 3,
    content: "Je vais bien aussi, merci! Qu'as-tu prévu pour aujourd'hui?",
    createdAt: "2022-01-10T09:10:00Z",
    updatedAt: "2022-01-10T09:10:00Z",
    isRead: false,
    sender: { username: "Alice", email: "carelli@gmail.com" },
    receiver: { username: "Kevin", email: "kevin@gmail.com" },
  },
  {
    id: 4,
    content: "Je dois travailler sur un projet toute la journée.",
    createdAt: "2022-01-10T09:15:00Z",
    updatedAt: "2022-01-10T09:15:00Z",
    isRead: false,
    sender: { username: "Kevin", email: "kevin@gmail.com" },
    receiver: { username: "Alice", email: "carelli@gmail.com" },
  },
  {
    id: 5,
    content: "Ça semble occupé! N'oublie pas de prendre des pauses.",
    createdAt: "2022-01-10T09:20:00Z",
    updatedAt: "2022-01-10T09:20:00Z",
    isRead: false,
    sender: { username: "Alice", email: "carelli@gmail.com" },
    receiver: { username: "Kevin", email: "kevin@gmail.com" },
  },
  {
    id: 6,
    content: "Oui, tu as raison. Je vais prendre des pauses régulières.",
    createdAt: "2022-01-10T09:25:00Z",
    updatedAt: "2022-01-10T09:25:00Z",
    isRead: false,
    sender: { username: "Kevin", email: "kevin@gmail.com" },
    receiver: { username: "Alice", email: "carelli@gmail.com" },
  },
];

export const messages3: Message[] = [
  {
    id: 1,
    content: "Salut Roger, comment ça va?",
    createdAt: "2022-01-12T14:00:00Z",
    updatedAt: "2022-01-12T14:00:00Z",
    isRead: true,
    sender: { username: "Alice", email: "carelli@gmail.com" },
    receiver: { username: "Roger", email: "roger@email.com" },
  },
  {
    id: 2,
    content: "Bonjour Alice, je vais bien, merci! Et toi?",
    createdAt: "2022-01-12T14:05:00Z",
    updatedAt: "2022-01-12T14:05:00Z",
    isRead: true,
    sender: { username: "Roger", email: "roger@email.com" },
    receiver: { username: "Alice", email: "carelli@gmail.com" },
  },
  {
    id: 3,
    content: "Je vais bien aussi, merci! Qu'as-tu prévu pour aujourd'hui?",
    createdAt: "2022-01-12T14:10:00Z",
    updatedAt: "2022-01-12T14:10:00Z",
    isRead: false,
    sender: { username: "Alice", email: "carelli@gmail.com" },
    receiver: { username: "Roger", email: "roger@email.com" },
  },
  {
    id: 4,
    content: "Je vais faire du vélo cet après-midi. Et toi?",
    createdAt: "2022-01-12T14:15:00Z",
    updatedAt: "2022-01-12T14:15:00Z",
    isRead: false,
    sender: { username: "Roger", email: "roger@email.com" },
    receiver: { username: "Alice", email: "carelli@gmail.com" },
  },
  {
    id: 5,
    content: "C'est génial! J'adore faire du vélo. Profite bien de ta balade!",
    createdAt: "2022-01-12T14:20:00Z",
    updatedAt: "2022-01-12T14:20:00Z",
    isRead: false,
    sender: { username: "Alice", email: "carelli@gmail.com" },
    receiver: { username: "Roger", email: "roger@email.com" },
  },
  {
    id: 6,
    content: "Merci, Alice! Je vais certainement en profiter.",
    createdAt: "2022-01-12T14:25:00Z",
    updatedAt: "2022-01-12T14:25:00Z",
    isRead: false,
    sender: { username: "Roger", email: "roger@email.com" },
    receiver: { username: "Alice", email: "carelli@gmail.com" },
  },
];
